[tool.poetry]
name = "runner"
version = "0.1.0"
description = ""
authors = ["Codegass <wchweichenhao@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
tensorflow = "^2.1.0rc2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
